### ISSUE TITLE
版本问题咨询

### ISSUE THREAD

**Issue by hu987610** [warmshao/ChatTTSPlus#23]
作者您好，我按照 readme 安装好环境后用python webui.py --cfg configs/infer/chattts_plus.yaml 启动报错
AttributeError: BertTokenizerFast has no attribute pad_token. Did you mean: '_pad_token'? #22
然后我把transformers 版本降到 transformers==4.42.3，可以启动，并可以用默认的 2222.pt进行声音合成。

但当我进行声音训练的时候，accelerate launch train_lora.py --config configs/train/train_voice_clone_lora.yaml

报错 ### ValueError: Attempting to unscale FP16 gradients. #6442

查了下又要升级transformers才能解决， when I update the latest PEFT and transformers, All problems are resolved.
但是一升级又包 AttributeError: BertTokenizerFast has no attribute pad_token. Did you mean: '_pad_token'? #22
想问下你本地的版本用的什么，会遇到这些问题吗？谢谢

**Comment by warmshao** [comment]
> 作者您好，我按照 readme 安装好环境后用python webui.py --cfg configs/infer/chattts_plus.yaml 启动报错 AttributeError: BertTokenizerFast has no attribute pad_token. Did you mean: '_pad_token'? #22 然后我把transformers 版本降到 transformers==4.42.3，可以启动，并可以用默认的 2222.pt进行声音合成。
> 
> 但当我进行声音训练的时候，accelerate launch train_lora.py --config configs/train/train_voice_clone_lora.yaml
> 
> 报错 ### ValueError: Attempting to unscale FP16 gradients. #6442
> 
> 查了下又要升级transformers才能解决， when I update the latest PEFT and transformers, All problems are resolved. 但是一升级又包 AttributeError: BertTokenizerFast has no attribute pad_token. Did you mean: '_pad_token'? #22 想问下你本地的版本用的什么，会遇到这些问题吗？谢谢

好像没有这个问题，晚点我确认一下版本以及这个bug

**Comment by hu987610** [comment]
> > 作者您好，我按照 readme 安装好环境后用python webui.py --cfg configs/infer/chattts_plus.yaml 启动报错 AttributeError: BertTokenizerFast has no attribute pad_token. Did you mean: '_pad_token'? #22 然后我把transformers 版本降到 transformers==4.42.3，可以启动，并可以用默认的 2222.pt进行声音合成。
> > 但当我进行声音训练的时候，accelerate launch train_lora.py --config configs/train/train_voice_clone_lora.yaml
> > 报错 ### ValueError: Attempting to unscale FP16 gradients. #6442
> > 查了下又要升级transformers才能解决， when I update the latest PEFT and transformers, All problems are resolved. 但是一升级又包 AttributeError: BertTokenizerFast has no attribute pad_token. Did you mean: '_pad_token'? #22 想问下你本地的版本用的什么，会遇到这些问题吗？谢谢
> 
> 好像没有这个问题，晚点我确认一下版本以及这个bug

好的谢谢，请问下这个有提供 api 版本吗？可以直接 postman 调用进行测试，我尝试了下用 fastAPI 把参数传到generate_audio，但是会报 
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by warmshao** [comment]
> 作者您好，我按照 readme 安装好环境后用python webui.py --cfg configs/infer/chattts_plus.yaml 启动报错 AttributeError: BertTokenizerFast has no attribute pad_token. Did you mean: '_pad_token'? #22 然后我把transformers 版本降到 transformers==4.42.3，可以启动，并可以用默认的 2222.pt进行声音合成。
> 
> 但当我进行声音训练的时候，accelerate launch train_lora.py --config configs/train/train_voice_clone_lora.yaml
> 
> 报错 ### ValueError: Attempting to unscale FP16 gradients. #6442
> 
> 查了下又要升级transformers才能解决， when I update the latest PEFT and transformers, All problems are resolved. 但是一升级又包 AttributeError: BertTokenizerFast has no attribute pad_token. Did you mean: '_pad_token'? #22 想问下你本地的版本用的什么，会遇到这些问题吗？谢谢

用的 4.42.4

**Comment by hu987610** [comment]
升级到4.42.4还是报错    raise ValueError("Attempting to unscale FP16 gradients.")。
torch 和 NumPy的版本方便帮忙看下吗？
